//@version=5
indicator("MultiVolatility", shorttitle="MultiVolatility")
import wanjo-tech/public/6 as public

//sourceLongInput = input.source(low, "Enter Long after crossing")
SP2PVTA(sym,period)=>request.security(sym,period,[close,volume,time/1000, close*volume])

symbol0 = syminfo.tickerid
[prz0a_d,vol0a_d,time0a_d,amt0a_d] = SP2PVTA(symbol0,'D')
[prz0a_15m,vol0a_15m,time0a_15m,amt0a_15m] = SP2PVTA(symbol0,'15')

bs365=100*math.sqrt(365)
bs252=100*math.sqrt(252)

//传统波动率：计算过去20天对数差分的标准差, 只对日线图才有少少意义，所以这里只在日线图画出
logdiff_d = math.log(prz0a_d / prz0a_d[1]) //对数差分
volatility20d = ta.stdev(logdiff_d, 20)
plot(timeframe.period=='D'?(bs252*volatility20d):na,color=color.green)

//对时波动率（基于D数据重新统计，用于在细周期图仍能画出“传统波动率”。但因为对时，所以跟传统会有区别）
[vlt20d_,lnr20d_] = public.StdTimeAligned(24*20,prz0a_d,vol0a_d,time0a_d,amt0a_d)
plot(bs365*vlt20d_,color=color.red)

//20天对时波动率（基于15分钟数据统计,所以比上面体现得更合理更滑一些）
[vlt20d,lnr20d] = public.StdTimeAligned(24*20,prz0a_15m,vol0a_15m,time0a_15m,amt0a_15m)
//plot(timeframe.period=='D'?na:(100*math.sqrt(365)*vlt20d),color=color.blue)
plot(bs365*vlt20d,color=color.blue,linewidth = 2) 

//七天对时波动率
[vlt7d,lnr7d] = public.StdTimeAligned(24*7,prz0a_15m,vol0a_15m,time0a_15m,amt0a_15m)
plot(bs365*vlt7d,color=color.black,linewidth = 2) 

//测试对时x天年化收益标准差，跟为跟差分数量级不一样，放在另一个副图；
// plot(bs365*lnr20d/20,color=color.orange)
// plot(bs365*lnr7d/7,color=color.purple)



